### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by VoR0220** [JacobEberhardt/ZoKrates#14]
What is the ZoKrates license?

**Comment by JacobEberhardt** [comment]
It's not finally decided yet, but I currently think LGPL-3.0 would fit very well.

**Comment by barryWhiteHat** [comment]
@Kyroy @Steffen93 @superphil0 Thoughts?

**Comment by superphil0** [comment]
sorry, not an expert

**Comment by Steffen93** [comment]
I agree with the LGPLv3 being a good choice.

**Comment by rbharath** [comment]
Very new here, but MIT license gives a lot of flexibility commercial adopters. Could help drive more developer support.

**Comment by VoR0220** [comment]
ZoKrates isn't meant to be forked and used in commercial applications though...it's a compiler...it's meant to be cutting edge cryptographic research, we would all benefit from it being LGPLv3...I think it would be a good choice to go with that.

**Comment by barryWhiteHat** [comment]
@superphil0 so software is all licensed. This tells the user how they want to use it. Sometimes these licenses are restrictive like windows and other times they are free like Linux. We want to license ZoKrates with a liberal license so that others can use and contribute to it. But since you contributed to it we need you to say its okay. Is it okay with you that we use the LGPLv3 license?

**Comment by superphil0** [comment]
Hey, thanks for explaining this again. Yes I agree with LGPLv3
