### ISSUE TITLE
Problems with division

### ISSUE THREAD

**Issue by Nanochrome** [JacobEberhardt/ZoKrates#27]
It seems as there is a problem with division.

If using the code:
`def main(a,b,c):
    	d = (1000 / a)
	e = (1000 / b)
	f = (1000 / c)
	return ((d + e) + f)
`
and 1000, 500 and 5000 as a,b and c respectively I get a very odd result.

d and e do both get the expected values, but f is  8755297148735710088898562298102910035419345760166413737479281674630323398247 which is definitely what not the expected value. 

Have I messed up or does it make sense to you?

**Comment by JacobEberhardt** [comment]
The result (allthough it may be unexpected) makes sense since the arithmetic operations work on prime fields here. Prime field elements are positive integers smaller a field prime p; there are no real numbers here.
That means, that f = 1000/c asks the question: which value of f * c = 1000 (mod p).
Your result says, that 875...247 * 5000 = 1000 (mod p)

You can check this here: https://www.wolframalpha.com/input/?i=(8755297148735710088898562298102910035419345760166413737479281674630323398247+*5000)+mod+21888242871839275222246405745257275088548364400416034343698204186575808495617
